spring:
  application:
    name: CommandeService
  data:
    mongodb:
      host: localhost
      port: 27017
      database: mangerDB
      username: user
      password: pass

server:
  port: 8080

application:
  jwt:
    prefix: "Bearer "
    header: "Authorization"
    key: "<J7Fz~X>-/co_*Y"
    expires: 846000000

  

