spring:
  application:
    name: CommandeService

  profiles:
    active: dev

server:
  port: 8080

application:
  jwt:
    prefix: "Bearer "
    header: "Authorization"
    key: "<J7Fz~X>-/co_*Y"
    expires: 846000000
