version: "3.9"

networks:
  backend: {}

services:
  becantine:
    depends_on:
      - mongodb
    container_name: becantine
    build: ./BECantine/ProduitService
    expose:
      - "8080"
    ports:
      - "8080:8080"
    networks:
      - backend
    restart: on-failure

  fecantine:
    build: ./FECantine
    expose:
      - "80"
    ports:
      - "80:80"

  mongodb:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: mangerDB
    expose:
      - 27017
    ports:
      - "27017:27017"
    networks:
      - backend
    volumes:
      - ./mongo_start/docker-entrypoint-initdb.d/script.js:/docker-entrypoint-initdb.d/init-mongo.js

    

